apiVersion: v1
kind: Service
metadata:
  name: cowork-service
  labels:
    app: cowork-app
spec:
  type: LoadBalancer
  selector:
    app: cowork-app
  ports:
    - protocol: TCP
      port: 5153
      targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowork-deployment
  labels:
    app: cowork-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cowork-app
  template:
    metadata:
      labels:
        app: cowork-app
    spec:
      containers:
      - name: coworkapp-eks-container
        # The $REPOSITORY_URI and $IMAGE_TAG placeholders will be replaced by actual values supplied by the build action in your workflow
        image: 120178829446.dkr.ecr.us-east-1.amazonaws.com/shob-uda-prj:0.0.1
        ports:
        - containerPort: 5153