apiVersion: v1
kind: Service
metadata:
  name: cowork-service
  labels:
    app: cowork-app
spec:
  type: LoadBalancer
  selector:
    app: cowork-app
  ports:
    - protocol: TCP
      port: 5153
      targetPort: 5153

---      

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowork-deployment
  labels:
    app: cowork-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cowork-app
  template:
    metadata:
      labels:
        app: cowork-app
    spec:
      containers:
      - name: coworkapp-eks-container
        # The $REPOSITORY_URI and $IMAGE_TAG placeholders will be replaced by actual values supplied by the build action in your workflow
        image: 120178829446.dkr.ecr.us-east-1.amazonaws.com/shob-uda-prj:0.0.15
        ports:
        - containerPort: 5153
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: db_port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: db_name           
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: db_password  